import type { Metadata } from "next";
import "./globals.css";
import { Pixelify_Sans } from "next/font/google";

const pixel = Pixelify_Sans({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Game Captcha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pixel.className} antialiased`}>{children}</body>
    </html>
  );
}
